name: "{{app_name.snakeCase()}}"
description: App mobile desenvolvido com arquitetura TITAN  (Clean + Modular + BLoC).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # --- ARQUITETURA CORE ---
  flutter_modular: ^6.3.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  result_dart: ^1.1.1
  
  # --- NETWORK & LOGS ---
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
  logger: ^2.4.0

  # --- STORAGE & DADOS LOCAIS ---
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.4

  # --- UI KIT & ASSETS (LEGADO + NOVO) ---
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  cached_network_image: ^3.4.1
  
  # Bibliotecas usadas nos Widgets antigos:
  remixicon: ^1.0.0
  loading_animation_widget: ^1.3.0
  shimmer: ^3.0.0

  # --- UTILITARIOS ---
  # Atualizado para evitar conflito com SDK recente
  intl: ^0.20.0
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  device_info_plus: ^10.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # --- TESTES E TOOLS ---
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  
  device_preview: ^1.2.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/i18n/